kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs
  fileSystemId: fs-066db691a94802167  # ✅ Ensure this is correct
  directoryPerms: "700"
  basePath: "/expense"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
mountOptions:
  - tls
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
