kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
  #soft limits
      requests:
        memory: "64Mi"
        cpu: "100m"
    #hard limits
      limits:
        memory: "128Mi"
        cpu: "150m"