apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    purpose: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: Deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: Deployment
    spec:
      containers:
      - name: nginx
        image: devsecopswithaws/nginx:1.0.0
        ports:
        - containerPort: 80